load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "reflections",
    data = ["//lib:LICENSE-Apache2.0"],
    visibility = ["//visibility:public"],
    exports = ["@reflections//jar"],
)