load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "equalsverifier",
    #    data = ["//lib:LICENSE-DO_NOT_DISTRIBUTE"],
    visibility = ["//visibility:public"],
    exports = ["@equalsverifier//jar"],
    runtime_deps = [
        #"//lib/easymock:cglib-3_2",
        #"//lib/easymock:objenesis",
    ],
)
